# Site Settings
title: JP Aesthetics
email: info@jpaesthetics.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



# Site Settings
url: "https://sitetitle.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "JP Aesthetics" # the name of your site, e.g. ACME Corp.
author: Dr Pooja Jassal-Prior
title_image: "/assets/images/logo.png"

# Social usernames/URLs
twitter: jpaesthetics
github: jpaesthetics
linkedin: jpaesthetics
instagram: jpaesthetics
facebook: jpaesthetics

disqus: "jpaesthetics"
google_analytics: 

# Build settings
markdown: kramdown
permalink: :title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

